In [1]:

#Import Pandas and NumPy
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Libraries imported successfully!")

Pandas version: 2.2.3
NumPy version: 2.1.3
Libraries imported successfully!

In [2]:
#Create a sample dataset

data = {
    "Name": ["Arun", "Priya", "Rahul", "Sneha", "Kiran", "Divya"],
    "Department": ["CSE", "DS", "CSE", "DS", "ECE", "DS"],
    "Marks": [85, 92, 76, 88, 67, 95],
    "Attendance": [90, 95, 80, 85, 70, 98]
}

df = pd.DataFrame(data)

print("Student Dataset:")
display(df)

Student Dataset:

    Name Department  Marks  Attendance
0   Arun        CSE     85          90
1  Priya         DS     92          95
2  Rahul        CSE     76          80
3  Sneha         DS     88          85
4  Kiran        ECE     67          70
5  Divya         DS     95          98

In [3]:
#Load CSV and Excel files
# Create sample files
df.to_csv("students.csv", index=False)
df.to_excel("students.xlsx", index=False)

# Load the CSV file
csv_data = pd.read_csv("students.csv")
print("CSV file loaded:")
display(csv_data)

# Load the Excel file
excel_data = pd.read_excel("students.xlsx")
print("Excel file loaded:")
display(excel_data)

CSV file loaded:

    Name Department  Marks  Attendance
0   Arun        CSE     85          90
1  Priya         DS     92          95
2  Rahul        CSE     76          80
3  Sneha         DS     88          85
4  Kiran        ECE     67          70
5  Divya         DS     95          98

Excel file loaded:

    Name Department  Marks  Attendance
0   Arun        CSE     85          90
1  Priya         DS     92          95
2  Rahul        CSE     76          80
3  Sneha         DS     88          85
4  Kiran        ECE     67          70
5  Divya         DS     95          98

In [4]:
#Perform filtering
high_scorers = df[df["Marks"] > 85]

print("Students scoring above 85:")
display(high_scorers)

Students scoring above 85:

    Name Department  Marks  Attendance
1  Priya         DS     92          95
3  Sneha         DS     88          85
5  Divya         DS     95          98

In [5]:
#Perform sorting
sorted_students = df.sort_values(
    by="Marks",
    ascending=False
)

print("Students sorted by marks:")
display(sorted_students)

Students sorted by marks:

    Name Department  Marks  Attendance
5  Divya         DS     95          98
1  Priya         DS     92          95
3  Sneha         DS     88          85
0   Arun        CSE     85          90
2  Rahul        CSE     76          80
4  Kiran        ECE     67          70

In [6]:
#Perform grouping
department_average = df.groupby(
    "Department"
)["Marks"].mean()

print("Average marks by department:")
display(department_average)

Average marks by department:

Department
CSE    80.500000
DS     91.666667
ECE    67.000000
Name: Marks, dtype: float64

In [7]:
#NumPy operations
marks = np.array([85, 92, 76, 88, 67, 95])

print("Marks:", marks)
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard deviation:", np.std(marks))

print("Marks above 85:", marks[marks > 85])
print("Marks sorted:", np.sort(marks))

Marks: [85 92 76 88 67 95]
Mean: 83.83333333333333
Maximum: 95
Minimum: 67
Standard deviation: 9.616247824501105
Marks above 85: [92 88 95]
Marks sorted: [67 76 85 88 92 95]